### ISSUE TITLE
API Connection Error during Initial Setup

### ISSUE THREAD

**Issue by brad07x** [explosivo22/rinnaicontrolr-ha#9]
Received the following error shown below during initial setup of the integration after entering credentials (verified working in Control-R app) into the pop-up.

`2021-07-10 00:08:26 ERROR (MainThread) [custom_components.rinnai] Error connecting to the Rinnai API: There was an error while requesting https://cognito-idp.us-east-1.amazonaws.com`

release 1.0.36, HACS 1.13.2/20210620205902. Running Home Assistant OS 6.1 on RPi, core-2021.7.1.

I've verified from the HA CLI (SSH AddOn) that the box has internet access (ping google.com), and that I can use cURL in verbose mode to see that the box can make a TLS/HTTPS connection to the URL from the error.

I also tried downgrading to an older release (1.0.34) via HACS reinstall - no luck.

Any thoughts on where I might start troubleshooting this problem or any pointers on increasing the log verbosity so I can try and figure out where this is breaking? 

I admit I am new to HA, but everything seemed to be going well/straightforward up to this point.

Really appreciate your work on this integration. Will be killer if I can get it working!

**Comment by explosivo22** [comment]
Could you try setting the integration up again? Looks like Rinnai may have been having some issues then as I got some logs in mine about errors reaching them. If it doesn't work this time, I will see about some debug logging.

**Comment by explosivo22** [comment]
I pushed an update that should update the dependencies to the newest versions which should include more logging information if this fails to setup for you again.

**Comment by brad07x** [comment]
Thanks for looking into this.

Updated to your 1.0.37 release, but still receive the 'Failed to Connect' error during the login stage. Same error in the logs, albeit with more info - 400 Bad Request.

2021-07-12 14:28:23 ERROR (MainThread) [custom_components.rinnai] Error connecting to the Rinnai API: There was the following error while requesting https://cognito-idp.us-east-1.amazonaws.com: 400, message='Bad Request', url=URL('https://cognito-idp.us-east-1.amazonaws.com')

Also tried reinstalling via HACS to 1.0.37 - no change. 

I verified again that I can log in to the Control-R app with the same credentials and from the same Internet connection (phone on WiFi).

**Comment by brad07x** [comment]
Don't know if this helps, but I can replicate the 400 Bad Request error during the authentication stage using your aiorinnai library. 

I was also able to add some lines in your api.py to enable request tracing for aiohttp which did make some additional debugging info available about the auth request that is being sent (method, URL, and headers), but I admit this may not be helpful or tell you anything new. 

First test - replicate 400 Bad Request error with aiorinnai library:

```
(env) root@rinnaitest:/opt/aiorinnai/021a8# python3 ./testing.py
Traceback (most recent call last):
  File "/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiorinnai/api.py", line 130, in _request
    resp.raise_for_status()
  File "/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://cognito-idp.us-east-1.amazonaws.com')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./testing.py", line 20, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./testing.py", line 10, in main
    api = await async_get_api("<e-mail redacted>", "<password redacted>")
  File "/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiorinnai/api.py", line 244, in async_get_api
    await wh.async_authenticate()
  File "/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiorinnai/api.py", line 148, in async_authenticate
    init_auth_response: dict = await self._request(
  File "/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiorinnai/api.py", line 134, in _request
    raise RequestError(f"There was the following error while requesting {url}: {err}") from err
aiorinnai.errors.RequestError: There was the following error while requesting https://cognito-idp.us-east-1.amazonaws.com: 400, message='Bad Request', url=URL('https://cognito-idp.us-east-1.amazonaws.com')
```

testing.py:
```
import asyncio

from aiohttp import ClientSession

from aiorinnai import async_get_api


async def main() -> None:
    """Run!"""
    api = await async_get_api("<USERNAME>", "<PASSWORD>")

    # Get user account information:
    user_info = await api.user.get_info()

    # Get device information
    first_device_id = user_info["devices"]["items"][0]["id"]
    device_info = await api.device.get_info(first_device_id)


asyncio.run(main())
```

diff of modified api.py compared to original:
```
(env) root@rinnaitest:/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiorinnai# diff api.orig api.py
6c6,7
< from aiohttp import ClientSession, ClientTimeout
---
> """Add TraceConfig to imports"""
> from aiohttp import ClientSession, ClientTimeout, TraceConfig
107a109,112
>         """Add aiohttp request tracing - set up logging portion"""
>         async def on_request_start(session, context, params):
>             logging.getLogger('aiohttp.client').debug(f'Starting request <{params}>')
>
125c130,135
<             session = ClientSession(timeout=ClientTimeout(total=120))
---
>             """Add aiohttp request tracing - set trace config and reference it as part of ClientSession()"""
>             logging.basicConfig(level=logging.DEBUG)
>             trace_config = TraceConfig()
>             trace_config.on_request_start.append(on_request_start)
>
>             session = ClientSession(trace_configs=[trace_config],timeout=ClientTimeout(total=120))
```

Second test - try again after adding config to enable request tracing for aiohttp. Note the additional DEBUG logging output line in the error below:

```
(env) root@rinnaitest:/opt/aiorinnai/021a8# python3 ./testing.py
DEBUG:aiohttp.client:Starting request <TraceRequestStartParams(method='post', url=URL('https://cognito-idp.us-east-1.amazonaws.com'), headers=<CIMultiDict('x-amz-user-agent': 'aws-amplify/0.1.x react-native', 'Content-Type': 'application/x-amz-json-1.1', 'x-amz-target': 'AWSCognitoIdentityProviderService.InitiateAuth')>)>
Traceback (most recent call last):
  File "/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiorinnai/api.py", line 135, in _request
    resp.raise_for_status()
  File "/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://cognito-idp.us-east-1.amazonaws.com')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./testing.py", line 20, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./testing.py", line 10, in main
    api = await async_get_api("<e-mail redacted>", "<password redacted>")
  File "/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiorinnai/api.py", line 249, in async_get_api
    await wh.async_authenticate()
  File "/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiorinnai/api.py", line 153, in async_authenticate
    init_auth_response: dict = await self._request(
  File "/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiorinnai/api.py", line 139, in _request
    raise RequestError(f"There was the following error while requesting {url}: {err}") from err
aiorinnai.errors.RequestError: There was the following error while requesting https://cognito-idp.us-east-1.amazonaws.com: 400, message='Bad Request', url=URL('https://cognito-idp.us-east-1.amazonaws.com')
(env) root@rinnaitest:/opt/aiorinnai/021a8#
```

**Comment by brad07x** [comment]
Figured out how to add in additional tracing at the end of the request - here's more detailed info:
```
DEBUG:aiohttp.client:Starting request <TraceRequestStartParams(method='post', url=URL('https://cognito-idp.us-east-1.amazonaws.com'), headers=<CIMultiDict('x-amz-user-agent': 'aws-amplify/0.1.x react-native', 'Content-Type': 'application/x-amz-json-1.1', 'x-amz-target': 'AWSCognitoIdentityProviderService.InitiateAuth')>)>, <namespace(trace_request_ctx=None)>, <<aiohttp.client.ClientSession object at 0x7f4995f00be0>>
DEBUG:aiohttp.client:Ending request <TraceRequestEndParams(method='post', url=URL('https://cognito-idp.us-east-1.amazonaws.com'), headers=<CIMultiDict('x-amz-user-agent': 'aws-amplify/0.1.x react-native', 'Content-Type': 'application/x-amz-json-1.1', 'x-amz-target': 'AWSCognitoIdentityProviderService.InitiateAuth')>, response=<ClientResponse(https://cognito-idp.us-east-1.amazonaws.com) [400 Bad Request]>
<CIMultiDictProxy('Date': 'Mon, 12 Jul 2021 20:47:24 GMT', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '67', 'Connection': 'keep-alive', 'x-amzn-RequestId': '180d5362-e743-4145-b12c-e961fe70d594', 'x-amzn-ErrorType': 'UserNotFoundException:', 'x-amzn-ErrorMessage': 'User does not exist.')>
)>, <namespace(trace_request_ctx=None)>, <<aiohttp.client.ClientSession object at 0x7f4995f00be0>>
```

Hmm -  **'x-amzn-ErrorMessage': 'User does not exist.'**

I'm using the same e-mail as I use to login to Control-R because I didn't see any documentation to do otherwise. Any thoughts?

**Comment by brad07x** [comment]
The last post about the non-existent user error clued me into the problem.

I didn't realize Rinnai had a new app (and likely cloud infra in AWS) for Control-R. I was still using their legacy cloud setup and firmware.

The new app (Rinnai 2.0) let me login with my old infra credentials, and after a 10 minute firmware update, I can now login with the same Rinnai credentials I was using before with your custom integration in HA. **_Success!_**

It seems like they have some processes baked into the onboarding for the new cloud for users of the old infra. Used the same credentials during the new app login, and the account in their AWS backend was created automagically!

Maybe it's worth including a quick note in the repo documentation about this integration supporting the new Control-R infrastructure only (https://play.google.com/store/apps/details?id=com.controlr & https://apps.apple.com/us/app/rinnai-control-r-2-0/id1180734911?app=itunes&ign-mpt=uo%3D4), not the legacy cloud (https://play.google.com/store/apps/details?id=com.rinnai.rinnai & https://apps.apple.com/us/app/rinnai-control-r/id1045235923?app=itunes&ign-mpt=uo%3D4) so big dummies like me don't lead you and other contributors on wild goose chases.

In case it is needed in the future, here's the extra few lines I used to increase the debug output for aiohttp that gave me the extra info about the response and specific error that I needed.

```
(env) root@rinnaitest:/opt/aiorinnai/021a8/env/lib/python3.8/site-packages/aiorinnai# diff api.orig api.py
6c6
< from aiohttp import ClientSession, ClientTimeout
---
> from aiohttp import ClientSession, ClientTimeout, TraceConfig
107a108,114
>         """Add aiohttp request tracing - set up logging portion"""
>         async def on_request_start(session, context, params):
>             logging.getLogger('aiohttp.client').debug(f'Starting request <{params}>, <{context}>, <{session}>')
>
>         async def on_request_end(session, context, params):
>             logging.getLogger('aiohttp.client').debug(f'Ending request <{params}>, <{context}>, <{session}>')
>
125c132,138
<             session = ClientSession(timeout=ClientTimeout(total=120))
---
>             """Add aiohttp request tracing - set trace config and reference it as part of ClientSession()"""
>             logging.basicConfig(level=logging.DEBUG)
>             trace_config = TraceConfig()
>             trace_config.on_request_start.append(on_request_start)
>             trace_config.on_request_end.append(on_request_end)
>
>             session = ClientSession(trace_configs=[trace_config],timeout=ClientTimeout(total=120))
```

**Comment by explosivo22** [comment]
Glad you figured this out. I will take into account the logging and the documentation that this works only if migrated to the Control-R 2.0 app
